version: '3.8'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./client/src
        target: /app/src
      - type: bind
        source: ./client/public
        target: /app/public
    command: npm run dev
